version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=tpachato
    volumes:
      - mysql-data:/var/local/mysql/data
      - db:/var/lib/mysql
    ports:
      - 3306:3306
      
  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: on-failure
    ports:
      - 8089:8089
    volumes:
      - .m2:/home/.m2
    stdin_open: true
    tty: true
    
volumes:
  db:
  mysql-data:
