version: "3"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    volumes:
      - db:/var/lib/mysql

  app_maven:
    depends_on:
      - mysqldb
    image: dalibouch/devops:latest
    container_name: dali
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" 
        }'
    volumes:
      - .m2:/root/.m2 
volumes:
  db:
  mysql-data:
