version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=tpachato
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
    volumes:
     - /home/vagrant/mysql/data:/var/lib/mysql

  spring_app:
    image: dalibouch/devops:latest
    container_name: achatspring
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" 
        }'
    ports:
     - 8089:8089
    depends_on:
     - mysqldb
