version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" }'
    volumes:
      - .m2:/home/.m2
    stdin_open: true
    tty: true
